# Generated by Django 3.2 on 2021-12-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='name',
        ),
    ]
