# Generated by Django 3.2 on 2021-12-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phnum',
            field=models.BigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
