# Generated by Django 3.2 on 2021-12-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0005_employee_phnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Eid',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
